---
default_language_version:
  python: python3.12
repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3.12
      - id: ruff-format
        language_version: python3.12

  # Python imports sorting
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black]
        language_version: python3.12

  # YAML formatting (using yamlfix instead of prettier)
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.17.0
    hooks:
      - id: yamlfix

  # General checks and security
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
        language_version: python3.12
      - id: detect-private-key
      - id: check-docstring-first
        language_version: python3.12
      - id: check-ast
        language_version: python3.12
      - id: requirements-txt-fixer
